Bump qemu 9.1.0 → 9.1.2
rancher-sandbox/rancher-desktop-qemu pull request #3
Opened 2024-11-27 20:04 UTC by jandubois

2024-11-27 22:10 UTC, mook-as approved these changes
Looks like homebrew replaced `pkg-config` with `pkgconf`; do we want to do that too?
https://github.com/Homebrew/homebrew-core/commit/e9d5c9f5a4029cdb4d17d64ccf710d7cd9cc93b2

2024-11-27 22:18 UTC, jandubois commented
> Looks like homebrew replaced `pkg-config` with `pkgconf`; do we want to do that too?

I doubt it makes a difference, but let's keep this as close as possible to the homebrew formula.

2024-11-27 22:46 UTC, mook-as requested changes
If we're picking up e9d5c9f5a4029cdb4d17d64ccf710d7cd9cc93b2 we should drop the `fails_with gcc: "5"` too.

2024-11-28 00:43 UTC, mook-as approved these changes

2024-11-28 00:44 UTC, merged